<?php
$data = array (
  0 => 
  array (
    'cat_id' => '24',
    'cat_name' => 'Perlenschmuck',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'Perlenring',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '91',
  ),
  2 => 
  array (
    'cat_id' => '18',
    'cat_name' => 'Perlenohrring',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '92',
  ),
  3 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Perlenarmband',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  4 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'Perlenohrstecker',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '71',
  ),
  5 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'Accessoires',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
  ),
  6 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Lose Perlen',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
  ),
  7 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'Perlenanhänger',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '336',
  ),
  8 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'Perlenkette',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '88',
  ),
);
?>