<?php
$data = array (
  24 => 
  array (
    'cat_id' => '24',
    'cat_name' => 'Perlenschmuck',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '24',
    'name' => 'Perlenschmuck',
  ),
  21 => 
  array (
    'cat_id' => '21',
    'cat_name' => 'Perlenring',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '91',
    'level' => 1,
    'id' => '21',
    'name' => 'Perlenring',
  ),
  18 => 
  array (
    'cat_id' => '18',
    'cat_name' => 'Perlenohrring',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '92',
    'level' => 1,
    'id' => '18',
    'name' => 'Perlenohrring',
  ),
  22 => 
  array (
    'cat_id' => '22',
    'cat_name' => 'Perlenarmband',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '22',
    'name' => 'Perlenarmband',
  ),
  19 => 
  array (
    'cat_id' => '19',
    'cat_name' => 'Perlenohrstecker',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '71',
    'level' => 1,
    'id' => '19',
    'name' => 'Perlenohrstecker',
  ),
  25 => 
  array (
    'cat_id' => '25',
    'cat_name' => 'Accessoires',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '3',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '9',
    'level' => 1,
    'id' => '25',
    'name' => 'Accessoires',
  ),
  26 => 
  array (
    'cat_id' => '26',
    'cat_name' => 'Lose Perlen',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '21',
    'level' => 1,
    'id' => '26',
    'name' => 'Lose Perlen',
  ),
  20 => 
  array (
    'cat_id' => '20',
    'cat_name' => 'Perlenanhänger',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '336',
    'level' => 1,
    'id' => '20',
    'name' => 'Perlenanhänger',
  ),
  17 => 
  array (
    'cat_id' => '17',
    'cat_name' => 'Perlenkette',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '7',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '88',
    'level' => 1,
    'id' => '17',
    'name' => 'Perlenkette',
  ),
);
?>